export const API_LOADING_START = 'API_LOADING_START';
export const API_LOADING_SUCCESS = 'API_LOADING_SUCCESS';
export const API_LOADING_FAILED = 'API_LOADING_FAILED';
export const NULLIFY_ERROR = 'NULLIFY_ERROR';
export const API_GET_PRODUCTDB = 'API_GET_PRODUCTDB';
export const API_REGIS_LOGIN = 'API_REGIS_LOGIN';
export const API_USER_LOGOUT = 'API_USER_LOGOUT';
